githubRepoOwner: hariom-qure
githubRepoName: spr
githubHost: github.com
requireChecks: true
requireApproval: false
mergeMethod: squash
mergeQueue: false
forceFetchTags: false
githubBranch: hariom/squash-merge-test
