githubRepoOwner: hariom-qure
githubRepoName: spr
githubRemote: origin
githubHost: github.com
githubBranch: master
requireChecks: false
requireApproval: false
mergeMethod: rebase
mergeQueue: false
forceFetchTags: false
